package app

import (
	"errors"
	"os"
	"sort"
	"strconv"
	"strings"
)

func serializeConfig(cfg config) map[string]string {
	values := map[string]string{
		"PIXELSMCP_TRANSPORT":       string(cfg.transport),
		"PIXELSMCP_ADDR":            cfg.addr,
		"PIXELSMCP_ENDPOINT":        cfg.mcpEndpoint,
		"PIXELSMCP_HEALTH_ENDPOINT": cfg.healthEndpoint,
		"PIXELSMCP_CORS_ORIGINS":    strings.Join(cfg.corsOrigins, ","),
		"PIXELSMCP_PROVIDER":        cfg.provider,
		"PIXELSMCP_BASE_URL":        cfg.baseURL,
		"PIXELSMCP_API_KEY":         cfg.apiKey,
		"PIXELSMCP_MODEL":           cfg.model,
		"PIXELSMCP_REFERENCE_MODEL": cfg.referenceModel,
		"PIXELSMCP_EXTRA_HEADERS":   encodeStringMap(cfg.extraHeaders),
		"PIXELSMCP_TIMEOUT":         cfg.timeout.String(),
		"PIXELSMCP_IMAGE_SAVE_DIR":  cfg.imageSaveDir,
	}

	return values
}

func encodeStringMap(values map[string]string) string {
	if len(values) == 0 {
		return ""
	}

	keys := make([]string, 0, len(values))
	for key := range values {
		if strings.TrimSpace(key) != "" {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteByte('{')
	for i, key := range keys {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(strconv.Quote(key))
		b.WriteByte(':')
		b.WriteString(strconv.Quote(values[key]))
	}
	b.WriteByte('}')
	return b.String()
}

func readFileIfExists(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if err == nil {
		return data, true, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	return nil, false, err
}

func restoreFile(path string, data []byte, existed bool) error {
	if !existed {
		return os.Remove(path)
	}
	return os.WriteFile(path, data, 0o600)
}

func writeEnvFile(path string, values map[string]string) error {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by PixelsMcp init for developer debugging\n")
	for _, key := range keys {
		b.WriteString(key)
		b.WriteByte('=')
		b.WriteString(strconv.Quote(values[key]))
		b.WriteByte('\n')
	}

	return os.WriteFile(path, []byte(b.String()), 0o600)
}
